const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const state={role:'user',view:'user-home',court:0,day:0,slot:null,payment:'QRIS',penaltyOn:true,penaltyMode:'adaptive',waived:false,equipment:{ball:0,vest:0,shoes:0,cones:0}};
const courts=[
  {name:'Lapangan Futsal A',meta:'Futsal • Indoor • Vinyl Pro',price:150000,icon:'⚽',rating:'4.9',type:'Futsal'},
  {name:'Lapangan Futsal B',meta:'Futsal • Semi Indoor • Sintetis',price:130000,icon:'⚽',rating:'4.8',type:'Futsal'},
  {name:'Badminton Court 1',meta:'Badminton • Indoor • Karpet',price:70000,icon:'🏸',rating:'4.9',type:'Badminton'},
  {name:'Basket Court',meta:'Basket • Outdoor • Acrylic',price:120000,icon:'🏀',rating:'4.7',type:'Basket'}
];
const days=[['Sen','14 Sep'],['Sel','15 Sep'],['Rab','16 Sep'],['Kam','17 Sep'],['Jum','18 Sep'],['Sab','19 Sep'],['Min','20 Sep']];
const slotTemplate=[
  {t:'08:00–09:00',s:'free',p:100000},{t:'09:00–10:00',s:'booked',p:100000},{t:'10:00–11:00',s:'free',p:100000},{t:'11:00–12:00',s:'pending',p:100000},{t:'12:00–13:00',s:'maint',p:100000},
  {t:'13:00–14:00',s:'free',p:120000},{t:'14:00–15:00',s:'free',p:120000},{t:'15:00–16:00',s:'booked',p:120000},{t:'16:00–17:00',s:'free',p:130000},{t:'17:00–18:00',s:'free',p:130000},
  {t:'18:00–19:00',s:'pending',p:170000},{t:'19:00–20:00',s:'free',p:170000},{t:'20:00–21:00',s:'booked',p:170000},{t:'21:00–22:00',s:'free',p:170000},{t:'22:00–23:00',s:'free',p:170000}
];
const equipment=[
  {id:'ball',name:'Bola Futsal',price:15000,stock:5,icon:'⚽'},
  {id:'vest',name:'Rompi Tim',price:5000,stock:14,icon:'🥋'},
  {id:'shoes',name:'Sepatu Futsal',price:25000,stock:8,icon:'👟'},
  {id:'cones',name:'Cone Training',price:10000,stock:10,icon:'🔺'}
];
const bookings=[
  {id:'BK-260914-015',user:'Rayhandi Tenri',court:'Futsal A',date:'14 Sep 2026',time:'19:00–21:00',pay:'QRIS',amount:365000,status:'Confirmed',fine:0},
  {id:'BK-260914-019',user:'Andika Pratama',court:'Futsal A',date:'14 Sep 2026',time:'19:00–20:00',pay:'Cash',amount:150000,status:'Playing',fine:20000},
  {id:'BK-260914-021',user:'Budi Santoso',court:'Badminton 1',date:'14 Sep 2026',time:'20:00–21:00',pay:'VA BCA',amount:90000,status:'Pending',fine:0},
  {id:'BK-260913-088',user:'Siti Rahma',court:'Futsal B',date:'13 Sep 2026',time:'18:00–20:00',pay:'QRIS',amount:310000,status:'Completed',fine:0},
  {id:'BK-260912-074',user:'Dimas Akbar',court:'Basket',date:'12 Sep 2026',time:'16:00–18:00',pay:'Cash',amount:250000,status:'Completed',fine:10000},
  {id:'BK-260911-061',user:'Rayhandi Tenri',court:'Badminton 1',date:'11 Sep 2026',time:'15:00–17:00',pay:'QRIS',amount:155000,status:'Completed',fine:0}
];
const transactions=[
  {id:'TRX-260914-128',booking:'BK-260914-015',user:'Rayhandi Tenri',method:'QRIS',base:365000,fine:0,status:'Paid',date:'14 Sep 2026'},
  {id:'TRX-260914-131',booking:'BK-260914-019',user:'Andika Pratama',method:'Cash',base:150000,fine:20000,status:'Paid',date:'14 Sep 2026'},
  {id:'TRX-260914-135',booking:'BK-260914-021',user:'Budi Santoso',method:'VA BCA',base:90000,fine:0,status:'Pending',date:'14 Sep 2026'},
  {id:'TRX-260913-116',booking:'BK-260913-088',user:'Siti Rahma',method:'QRIS',base:310000,fine:0,status:'Paid',date:'13 Sep 2026'},
  {id:'TRX-260912-102',booking:'BK-260912-074',user:'Dimas Akbar',method:'Cash',base:250000,fine:10000,status:'Paid',date:'12 Sep 2026'}
];
const adminEquipment=[
  {icon:'⚽',name:'Bola Futsal Pro',cat:'Bola',total:10,rented:6,damaged:1,price:15000,status:'Normal'},
  {icon:'🥋',name:'Rompi Tim',cat:'Training',total:24,rented:14,damaged:0,price:5000,status:'Normal'},
  {icon:'👟',name:'Sepatu Futsal',cat:'Footwear',total:12,rented:8,damaged:2,price:25000,status:'Kritis'},
  {icon:'🔺',name:'Cone Training',cat:'Training',total:18,rented:10,damaged:0,price:10000,status:'Normal'},
  {icon:'🏸',name:'Raket Badminton',cat:'Badminton',total:14,rented:9,damaged:1,price:20000,status:'Kritis'},
  {icon:'🏀',name:'Bola Basket',cat:'Basket',total:8,rented:5,damaged:0,price:15000,status:'Kritis'}
];
function qs(s){return document.querySelector(s)}function qsa(s){return [...document.querySelectorAll(s)]}
function toast(msg){const el=qs('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2300)}
function statusTag(status){const map={Confirmed:'success',Paid:'success',Playing:'success',Completed:'neutral',Pending:'pending',Cancelled:'danger'};return `<span class="tag ${map[status]||'neutral'}">${status.toUpperCase()}</span>`}
function switchView(id){state.view=id;qsa('.view').forEach(v=>v.classList.toggle('active',v.id===id));qsa('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const btn=qs(`[data-view="${id}"]`);const name=btn?btn.querySelector('b').textContent:id;qs('#crumb').textContent=`${state.role.toUpperCase()} / ${name.toUpperCase()}`;qs('#pageTitle').textContent=state.role==='user'?(id==='user-home'?'Selamat datang kembali':name):name;window.scrollTo({top:0,behavior:'smooth'});}
qsa('[data-role]').forEach(b=>b.addEventListener('click',()=>{state.role=b.dataset.role;qsa('[data-role]').forEach(x=>x.classList.toggle('active',x===b));qs('#userNav').classList.toggle('hidden',state.role!=='user');qs('#adminNav').classList.toggle('hidden',state.role!=='admin');qs('#roleLabel').textContent=state.role==='user'?'User':'Administrator';switchView(state.role==='user'?'user-home':'admin-home');}));
qsa('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));qsa('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));
function renderCourts(){qs('#courtList').innerHTML=courts.map((c,i)=>`<button class="court-item ${i===state.court?'active':''}" data-court="${i}"><span class="court-icon">${c.icon}</span><span><b>${c.name}</b><span>${c.type} • ${rupiah(c.price)}/jam</span></span></button>`).join('');qsa('[data-court]').forEach(b=>b.onclick=()=>{state.court=+b.dataset.court;state.slot=null;renderCourts();renderSchedule();});}
function renderSchedule(){const c=courts[state.court];qs('#selectedCourtName').textContent=c.name;qs('#selectedCourtMeta').textContent=c.meta;qs('#weekStrip').innerHTML=days.map((d,i)=>`<button class="day-chip ${i===state.day?'active':''}" data-day="${i}"><b>${d[0]}</b><span>${d[1]}</span></button>`).join('');qsa('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;renderSchedule()});const priceFactor=state.court===2?.6:state.court===3?.8:state.court===1?.9:1;qs('#slotGrid').innerHTML=slotTemplate.map((s,i)=>{let status=s.s;if((state.day+i+state.court)%11===0)status='booked';const p=Math.round(s.p*priceFactor/5000)*5000;const label=status==='free'?rupiah(p):status==='booked'?'Sudah dibooking':status==='pending'?'Menunggu bayar':'Maintenance';return `<button class="slot ${status}" ${status!=='free'?'disabled':''} data-slot="${i}" data-price="${p}"><b>${s.t}</b><span>${label}</span></button>`}).join('');qsa('.slot.free').forEach(b=>b.onclick=()=>openCheckout(+b.dataset.slot,+b.dataset.price));}
function renderVenues(){qs('#venueGrid').innerHTML=courts.slice(0,3).map((c,i)=>`<article class="venue-card"><div class="venue-visual"></div><div class="venue-body"><h4>${c.name}</h4><p>${c.meta}. Cocok untuk booking reguler, komunitas, dan latihan.</p><div class="venue-footer"><div><b>⭐ ${c.rating}</b><span> • mulai ${rupiah(c.price)}</span></div><button class="btn soft tiny" data-venue="${i}">Pilih</button></div></div></article>`).join('');qsa('[data-venue]').forEach(b=>b.onclick=()=>{state.court=+b.dataset.venue;renderCourts();renderSchedule();window.scrollTo({top:150,behavior:'smooth'})});}
function openCheckout(slotIndex,price){state.slot={index:slotIndex,price,time:slotTemplate[slotIndex].t};state.equipment={ball:0,vest:0,shoes:0,cones:0};renderCheckout();qs('#checkoutDrawer').classList.add('open');}
function renderCheckout(){const c=courts[state.court],d=days[state.day];qs('#checkoutSummary').innerHTML=`<div><span>Lapangan</span><b>${c.name}</b></div><div><span>Tanggal</span><b>${d[0]}, ${d[1]} 2026</b></div><div><span>Waktu</span><b>${state.slot.time}</b></div><div><span>Harga lapangan</span><b>${rupiah(state.slot.price)}</b></div>`;qs('#checkoutEquipment').innerHTML=equipment.map(e=>`<div class="equipment-row"><div><b>${e.icon} ${e.name}</b><span>${rupiah(e.price)} • tersedia ${e.stock}</span></div><div class="qty-control"><button data-qty="${e.id}" data-dir="-1">−</button><b>${state.equipment[e.id]}</b><button data-qty="${e.id}" data-dir="1">+</button></div></div>`).join('');qsa('[data-qty]').forEach(b=>b.onclick=()=>{const id=b.dataset.qty,dir=+b.dataset.dir,max=equipment.find(x=>x.id===id).stock;state.equipment[id]=Math.max(0,Math.min(max,state.equipment[id]+dir));renderCheckout()});qsa('#paymentGrid button').forEach(b=>b.classList.toggle('active',b.dataset.pay===state.payment));const eq=equipment.reduce((sum,e)=>sum+state.equipment[e.id]*e.price,0),admin=state.payment==='Bayar di Lokasi'?0:5000,total=state.slot.price+eq+admin;qs('#checkoutTotals').innerHTML=`<div><span>Lapangan</span><b>${rupiah(state.slot.price)}</b></div><div><span>Perlengkapan</span><b>${rupiah(eq)}</b></div><div><span>Biaya layanan</span><b>${rupiah(admin)}</b></div><div class="grand"><span>Total</span><b>${rupiah(total)}</b></div>`;}
qsa('#paymentGrid button').forEach(b=>b.onclick=()=>{state.payment=b.dataset.pay;renderCheckout()});qsa('[data-close="checkout"]').forEach(b=>b.onclick=()=>qs('#checkoutDrawer').classList.remove('open'));
qs('#confirmBooking').onclick=()=>{qs('#checkoutDrawer').classList.remove('open');toast(state.payment==='Bayar di Lokasi'?'Booking dibuat • bayar di kasir saat datang':'Booking dibuat • simulasi pembayaran online berhasil');setTimeout(()=>switchView('my-bookings'),400)};
function renderUserBookings(){const rows=[bookings[0],{...bookings[2],user:'Rayhandi Tenri',court:'Badminton 1'},bookings[5],{...bookings[3],user:'Rayhandi Tenri'}, {...bookings[4],user:'Rayhandi Tenri',fine:0}, {...bookings[1],user:'Rayhandi Tenri',status:'Completed',fine:0}];qs('#userBookingList').innerHTML=rows.map(b=>`<article class="booking-row"><div><h4>${b.court}</h4><p>${b.id} • ${b.date}</p></div><div class="meta"><span>Jadwal</span><b>${b.time}</b></div><div class="money"><span>Total</span><b>${rupiah(b.amount+b.fine)}</b></div><div class="row-actions">${statusTag(b.status)}<button class="btn ghost tiny" data-invoice="${b.id}">Invoice</button></div></article>`).join('');bindInvoiceButtons();}
function renderTransactions(){qs('#userTransactionRows').innerHTML=transactions.filter((_,i)=>i!==1||true).map(t=>`<tr><td><b>${t.id}</b><span>${t.booking}</span></td><td>${t.date}</td><td>${t.booking}</td><td>${t.method}</td><td><b>${rupiah(t.base+t.fine)}</b></td><td>${statusTag(t.status)}</td><td><button class="btn ghost tiny" data-invoice="${t.booking}">Invoice</button></td></tr>`).join('');qs('#adminTransactionRows').innerHTML=transactions.map(t=>`<tr><td><b>${t.id}</b><span>${t.date}</span></td><td>${t.booking}</td><td>${t.user}</td><td>${t.method}</td><td>${rupiah(t.base)}</td><td>${t.fine?`<b style="color:#bd514c">${rupiah(t.fine)}</b>`:'—'}</td><td><b>${rupiah(t.base+t.fine)}</b></td><td>${statusTag(t.status)}</td></tr>`).join('');bindInvoiceButtons();}
function renderAdminBookings(){qs('#adminBookingRows').innerHTML=bookings.map(b=>`<tr><td><b>${b.id}</b><span>${b.date}</span></td><td>${b.user}</td><td>${b.court}</td><td><b>${b.time}</b></td><td><span>${b.pay}</span><b>${rupiah(b.amount)}</b></td><td>${b.fine?`<span class="tag danger">${rupiah(b.fine)}</span>`:'—'}</td><td>${statusTag(b.status)}</td><td><button class="btn ghost tiny" data-invoice="${b.id}">Detail</button></td></tr>`).join('');bindInvoiceButtons();}
function renderLive(){const items=[['18:00','Futsal B','Siti Rahma • 18:00–20:00','Playing'],['19:00','Futsal A','Andika Pratama • overtime','Warning'],['19:00','Badminton 1','Rio Mahendra • 19:00–20:00','Playing'],['20:00','Basket Court','Persiapan booking berikutnya','Next']];qs('#liveSchedule').innerHTML=items.map(x=>`<div class="live-item"><div class="time">${x[0]}</div><div><b>${x[1]}</b><span>${x[2]}</span></div><span class="tag ${x[3]==='Warning'?'danger':x[3]==='Next'?'pending':'success'}">${x[3].toUpperCase()}</span></div>`).join('');}
function renderCharts(){const vals=[[56,20],[72,26],[68,30],[84,22],[78,35],[92,38],[88,31]];qs('#revenueChart').innerHTML=vals.map((v,i)=>`<div class="chart-col"><i style="height:${v[0]}%"></i><i class="offline" style="height:${v[1]}%"></i><span>${['Sen','Sel','Rab','Kam','Jum','Sab','Min'][i]}</span></div>`).join('');qs('#criticalStock').innerHTML=adminEquipment.filter(x=>x.status==='Kritis').map(x=>{const available=x.total-x.rented-x.damaged,p=Math.max(8,available/x.total*100);return `<div class="stock-row"><div><b>${x.name}</b><span>${available} tersedia dari ${x.total}</span></div><div class="stock-meter"><i style="width:${p}%"></i></div><span class="tag pending">KRITIS</span></div>`}).join('');const occ=[['Futsal A',86],['Futsal B',72],['Badminton 1',68],['Basket',51]];qs('#occupancyBars').innerHTML=occ.map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar-track"><i style="width:${x[1]}%"></i></div><b>${x[1]}%</b></div>`).join('');}
function renderEquipment(){qs('#equipmentGrid').innerHTML=adminEquipment.map(e=>{const avail=e.total-e.rented-e.damaged;return `<article class="equipment-card"><div class="equipment-head"><span class="equipment-icon">${e.icon}</span><span class="tag ${e.status==='Kritis'?'pending':'success'}">${e.status.toUpperCase()}</span></div><h4>${e.name}</h4><p>${e.cat} • disewakan per booking. Ketersediaan dihitung terhadap waktu sewa yang sama.</p><div class="equipment-stats"><div><span>Total</span><b>${e.total}</b></div><div><span>Disewa</span><b>${e.rented}</b></div><div><span>Tersedia</span><b>${avail}</b></div></div><div class="equipment-footer"><b>${rupiah(e.price)} / booking</b><button class="btn ghost tiny">Kelola</button></div></article>`}).join('');}
function renderCalendar(){const hours=['08','09','10','11','12','13','14','15','16','17','18'];let html=`<div class="calendar-grid"><div class="cal-cell cal-head">Lapangan</div>${hours.map(h=>`<div class="cal-cell cal-head">${h}:00</div>`).join('')}`;courts.forEach((c,ci)=>{html+=`<div class="cal-cell cal-name">${c.name}</div>`;hours.forEach((h,hi)=>{const key=(ci*3+hi)%9;let cell='';if(key===1||key===4)cell=`<div class="cal-book">Booked</div>`;else if(key===6)cell=`<div class="cal-book pending">Pending</div>`;else if(key===8&&ci===0)cell=`<div class="cal-book maint">Maintenance</div>`;html+=`<div class="cal-cell">${cell}</div>`});});html+='</div>';qs('#adminCalendar').innerHTML=html;}
function calcPenalty(){if(!state.penaltyOn||state.waived){qs('#penaltyTotal').textContent='Rp0';qs('#penaltyCalcText').textContent=state.waived?'Dibebaskan oleh admin':'Denda global nonaktif';qs('#caseStatus').textContent=state.waived?'DIBEBASKAN':'DENDA OFF';qs('#caseStatus').className='tag neutral';return 0}const grace=+qs('#graceMinutes').value||0,interval=+qs('#penaltyInterval').value||10,amount=+qs('#penaltyAmount').value||0,max=+qs('#penaltyMax').value||9999999,late=17,billable=Math.max(0,late-grace),count=Math.ceil(billable/interval),total=Math.min(max,count*amount);qs('#penaltyTotal').textContent=rupiah(total);qs('#penaltyCalcText').textContent=`${count} interval × ${rupiah(amount)} • toleransi ${grace} menit`;qs('#caseStatus').textContent=total?'DENDA AKTIF':'TIDAK KENA';qs('#caseStatus').className=`tag ${total?'danger':'success'}`;return total}
qs('#globalPenaltyToggle').onclick=()=>{state.penaltyOn=!state.penaltyOn;qs('#globalPenaltyToggle').classList.toggle('on',state.penaltyOn);qs('#penaltyGlobalBadge').textContent=state.penaltyOn?'GLOBAL ON':'GLOBAL OFF';qs('#penaltyGlobalBadge').className=`tag ${state.penaltyOn?'success':'neutral'}`;calcPenalty();toast(`Denda global ${state.penaltyOn?'diaktifkan':'dinonaktifkan'}`)};qsa('[data-penalty-mode]').forEach(b=>b.onclick=()=>{state.penaltyMode=b.dataset.penaltyMode;qsa('[data-penalty-mode]').forEach(x=>x.classList.toggle('active',x===b));toast(state.penaltyMode==='adaptive'?'Mode adaptif aktif':'Mode manual admin aktif')});['#graceMinutes','#penaltyAmount','#penaltyInterval','#penaltyMax'].forEach(id=>qs(id).addEventListener('input',calcPenalty));qs('#waivePenalty').onclick=()=>{state.waived=true;calcPenalty();renderAudit();toast('Denda dibebaskan dan dicatat ke audit log')};qs('#confirmPenalty').onclick=()=>{state.waived=false;calcPenalty();renderAudit(true);toast('Denda dikonfirmasi')};
function renderAudit(confirmed=false){const total=calcPenalty();const rows=[['14 Sep • 20:18','BK-260914-019',state.waived?'Denda dibebaskan':confirmed?'Denda dikonfirmasi':'Denda terdeteksi',state.waived?'Rp0':rupiah(total),'Admin','Booking berikutnya terdampak'],['13 Sep • 21:12','BK-260913-088','Denda otomatis OFF','Rp0','System','Tidak ada booking setelahnya'],['12 Sep • 18:14','BK-260912-074','Denda dikonfirmasi','Rp10.000','Admin','Overlap 9 menit setelah toleransi']];qs('#auditRows').innerHTML=rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===2?`<b>${x}</b>`:x}</td>`).join('')}</tr>`).join('');}
function bindInvoiceButtons(){qsa('[data-invoice]').forEach(b=>b.onclick=()=>openInvoice(b.dataset.invoice))}
function openInvoice(id){const b=bookings.find(x=>x.id===id)||bookings[0],t=transactions.find(x=>x.booking===b.id);const total=(t?t.base:b.amount)+(t?t.fine:b.fine||0);qs('#invoiceBody').innerHTML=`<div class="invoice-header"><div><h3>INVOICE</h3><p>${t?t.id:'TRX-DEMO-001'}</p></div><div style="text-align:right"><b>${statusTag(t?t.status:'Paid')}</b><p>${b.date}</p></div></div><div class="invoice-box"><div><span>Booking</span><b>${b.id}</b></div><div><span>Pelanggan</span><b>${b.user}</b></div><div><span>Lapangan</span><b>${b.court}</b></div><div><span>Jadwal</span><b>${b.date} • ${b.time}</b></div><div><span>Metode</span><b>${t?t.method:b.pay}</b></div></div><div class="invoice-box"><div><span>Subtotal booking</span><b>${rupiah(t?t.base:b.amount)}</b></div><div><span>Denda</span><b>${rupiah(t?t.fine:b.fine||0)}</b></div></div><div class="invoice-total"><span>Total</span><b>${rupiah(total)}</b></div>`;qs('#invoiceModal').classList.add('open')}
qsa('[data-close="invoice"]').forEach(b=>b.onclick=()=>qs('#invoiceModal').classList.remove('open'));qs('#printInvoice').onclick=()=>window.print();
function init(){renderCourts();renderSchedule();renderVenues();renderUserBookings();renderTransactions();renderAdminBookings();renderLive();renderCharts();renderEquipment();renderCalendar();renderAudit();bindInvoiceButtons();}
init();
