const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const state={role:'user',court:'Futsal A',courtRate:150000,duration:3,start:'19:00',date:'2026-09-20',equipment:{ball:1,vest:10,shoe:0},invoiceTotal:515000,invoiceId:'BK-260915-021',proof:null,proofHash:null,penalty:true};
const courts=[{name:'Futsal A',meta:'Indoor • Vinyl Pro',rate:150000},{name:'Futsal B',meta:'Indoor • Rumput sintetis',rate:140000},{name:'Badminton 1',meta:'Indoor • Karpet',rate:75000},{name:'Basket A',meta:'Semi indoor',rate:120000}];
const equipment=[{id:'ball',name:'Bola Futsal',price:15000,stock:5},{id:'vest',name:'Rompi',price:5000,stock:20},{id:'shoe',name:'Sepatu Futsal',price:25000,stock:8}];
let bookings=JSON.parse(localStorage.getItem('arenaBookings')||'null')||[
{id:'BK-260915-021',user:'Rayhandi Tenri',court:'Futsal A',date:'20 Sep 2026',time:'19:00–22:00',total:515000,payment:'AWAITING_PAYMENT',booking:'PENDING',proof:null,screening:null,audit:[]},
{id:'BK-260915-014',user:'Dina Amelia',court:'Badminton 1',date:'15 Sep 2026',time:'18:00–20:00',total:180000,payment:'PROOF_SUBMITTED',booking:'PENDING',proof:{name:'bukti_dina.jpg',hash:'demo-dina'},screening:{score:92,amountMatch:true,reference:true,fileOk:true,duplicate:false},audit:['Bukti diupload 14:22']},
{id:'BK-260915-010',user:'Budi Santoso',court:'Futsal B',date:'15 Sep 2026',time:'20:00–22:00',total:300000,payment:'PAID',booking:'CONFIRMED',proof:{name:'bukti_budi.jpg',hash:'demo-budi'},screening:{score:96,amountMatch:true,reference:true,fileOk:true,duplicate:false},audit:['Admin approved 13:10']}
];
function save(){localStorage.setItem('arenaBookings',JSON.stringify(bookings));}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const map={home:['USER / BERANDA','Booking lapangan tanpa ribet'],booking:['USER / BOOKING','Pilih jadwal'],checkout:['USER / CHECKOUT','Selesaikan data booking'],payments:['USER / PEMBAYARAN','Pembayaran & bukti transfer'],mybooking:['USER / BOOKING SAYA','Status booking'], 'admin-home':['ADMIN / OVERVIEW','Operasional hari ini'],'admin-verification':['ADMIN / VERIFIKASI','Verifikasi pembayaran'],'admin-bookings':['ADMIN / BOOKING','Semua booking'],'admin-transactions':['ADMIN / TRANSAKSI','Riwayat transaksi'],'admin-penalty':['ADMIN / DENDA','Denda adaptif']};const m=map[view]||['ARENA BOOK','Dashboard'];$('#crumb').textContent=m[0];$('#title').textContent=m[1];window.scrollTo({top:0,behavior:'smooth'});renderAll();}
$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$$('.nav-btn').forEach(b=>b.onclick=()=>nav(b.dataset.view));
$$('.role-btn').forEach(b=>b.onclick=()=>{state.role=b.dataset.role;$$('.role-btn').forEach(x=>x.classList.toggle('active',x===b));$('#userNav').classList.toggle('hidden',state.role!=='user');$('#adminNav').classList.toggle('hidden',state.role!=='admin');$('#roleText').textContent=state.role==='user'?'User':'Admin';nav(state.role==='user'?'home':'admin-home')});
function renderCourts(){const box=$('#courtList');box.innerHTML=courts.map(c=>`<button class="court-btn ${c.name===state.court?'active':''}" data-court="${c.name}"><b>${c.name}</b><span>${c.meta} • ${rupiah(c.rate)}/jam</span></button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const c=courts.find(x=>x.name===b.dataset.court);state.court=c.name;state.courtRate=c.rate;$('#courtTitle').textContent=c.name;renderCourts();updateSelection()})}
function renderWeek(){const days=[['Sen','14'],['Sel','15'],['Rab','16'],['Kam','17'],['Jum','18'],['Sab','19'],['Min','20']];$('#week').innerHTML=days.map(d=>`<button class="day ${d[1]==='20'?'active':''}"><span>${d[0]}</span><b>${d[1]}</b></button>`).join('')}
function renderSlots(){const slots=[['16:00','free'],['17:00','free'],['18:00','free'],['19:00','selected'],['20:00','selected'],['21:00','selected'],['22:00','booked'],['23:00','pending']];$('#slots').innerHTML=slots.map(([t,s])=>`<button class="slot ${s}"><b>${t}</b><span>${s==='free'||s==='selected'?rupiah(state.courtRate):s==='booked'?'Booked':'Pending'}</span></button>`).join('')}
function updateSelection(){state.duration=+$('#duration').value;state.start=$('#startTime').value;state.date=$('#bookingDate').value;const start=+state.start.split(':')[0],end=start+state.duration;$('#selectionText').textContent=`20 Sep 2026 • ${state.start}–${String(end).padStart(2,'0')}:00 • ${state.duration} jam`;$('#courtPrice').textContent=rupiah(state.courtRate*state.duration);renderSlots();updateTotals()}
['duration','startTime','bookingDate'].forEach(id=>$('#'+id).addEventListener('change',updateSelection));
function renderEquipment(){const box=$('#equipmentList');box.innerHTML=equipment.map(e=>`<div class="equipment-item"><div><b>${e.name}</b><span>${rupiah(e.price)} / booking • stok ${e.stock}</span></div><b>${rupiah(e.price*(state.equipment[e.id]||0))}</b><div class="qty"><button data-dec="${e.id}">−</button><b>${state.equipment[e.id]||0}</b><button data-inc="${e.id}">+</button></div></div>`).join('');box.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{const e=equipment.find(x=>x.id===b.dataset.inc);state.equipment[e.id]=Math.min(e.stock,(state.equipment[e.id]||0)+1);renderEquipment();updateTotals()});box.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const id=b.dataset.dec;state.equipment[id]=Math.max(0,(state.equipment[id]||0)-1);renderEquipment();updateTotals()})}
function equipmentTotal(){return equipment.reduce((a,e)=>a+e.price*(state.equipment[e.id]||0),0)}
function updateTotals(){const court=state.courtRate*state.duration,eq=equipmentTotal();state.invoiceTotal=court+eq;$('#sumCourt').textContent=rupiah(court);$('#sumEquipment').textContent=rupiah(eq);$('#grandTotal').textContent=rupiah(state.invoiceTotal);$('#invoiceAmount').textContent=rupiah(state.invoiceTotal);$('#paymentTotal').textContent=rupiah(state.invoiceTotal);$('#transferAmount').value=state.invoiceTotal;$('#orderTime').textContent=`${state.start} — ${String(+state.start.split(':')[0]+state.duration).padStart(2,'0')}:00`}
$('#continueCheckout').onclick=()=>{updateSelection();nav('checkout')};
$('#createInvoice').onclick=()=>{if(!$('#agree').checked)return toast('Setujui data booking terlebih dahulu.');const existing=bookings.find(b=>b.id===state.invoiceId);const obj={id:state.invoiceId,user:$('#name').value||'User',court:state.court,date:'20 Sep 2026',time:`${state.start}–${String(+state.start.split(':')[0]+state.duration).padStart(2,'0')}:00`,total:state.invoiceTotal,payment:'AWAITING_PAYMENT',booking:'PENDING',proof:null,screening:null,audit:['Booking dibuat dari website']};if(existing)Object.assign(existing,obj);else bookings.unshift(obj);save();$('#paymentInvoiceId').textContent='#'+obj.id;renderAll();nav('payments');toast('Booking dibuat. Slot ditahan sementara.')};
function timelineFor(b){const submitted=b.payment!=='AWAITING_PAYMENT';const decided=['PAID','REJECTED'].includes(b.payment);return `<div class="timeline-item done"><b>Booking dibuat</b><span>Invoice ${b.id}</span></div><div class="timeline-item ${submitted?'done':''}"><b>Bukti transfer dikirim</b><span>${submitted?'Sudah diterima':'Menunggu upload'}</span></div><div class="timeline-item ${decided?'done':''}"><b>Verifikasi admin</b><span>${b.payment==='PAID'?'Dana terkonfirmasi':b.payment==='REJECTED'?'Bukti ditolak':'Belum diputuskan'}</span></div><div class="timeline-item ${b.booking==='CONFIRMED'?'done':''}"><b>Booking confirmed</b><span>${b.booking==='CONFIRMED'?'Siap digunakan':'Menunggu pembayaran valid'}</span></div>`}
async function hashFile(file){const data=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
$('#pickFile').onclick=e=>{e.preventDefault();$('#proofFile').click()};$('#proofFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;state.proof=f;state.proofHash=await hashFile(f);const url=URL.createObjectURL(f);$('#filePreview').classList.remove('hidden');$('#filePreview').innerHTML=`<img src="${url}"><div><b>${f.name}</b><span>${(f.size/1024).toFixed(0)} KB • ${f.type}</span></div><span>Siap dikirim</span>`};
$('#submitProof').onclick=async()=>{const b=bookings.find(x=>x.id===state.invoiceId)||bookings[0];if(!state.proof)return toast('Pilih file bukti transfer dulu.');const amount=+$('#transferAmount').value,ref=$('#reference').value.trim();const fileOk=state.proof.size<=5*1024*1024&&/^image\/(jpeg|png|webp)$/.test(state.proof.type);const amountMatch=amount===b.total;const duplicate=bookings.some(x=>x.proof?.hash&&x.proof.hash===state.proofHash&&x.id!==b.id);const score=Math.max(0,100-(fileOk?0:40)-(amountMatch?0:35)-(ref?0:15)-(duplicate?45:0));b.payment='PROOF_SUBMITTED';b.proof={name:state.proof.name,hash:state.proofHash,size:state.proof.size,type:state.proof.type,bank:$('#senderBank').value,reference:ref,amount};b.screening={score,fileOk,amountMatch,reference:!!ref,duplicate};b.audit.push(`Bukti diupload ${new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`);save();renderAll();toast('Bukti masuk antrean verifikasi admin.')};
function statusChip(s){const c=s==='PAID'||s==='CONFIRMED'?'success':s==='REJECTED'||s==='CANCELLED'?'danger':s==='PROOF_SUBMITTED'?'info':'waiting';return `<span class="status ${c}">${s.replaceAll('_',' ')}</span>`}
function renderPayment(){const b=bookings.find(x=>x.id===state.invoiceId)||bookings[0];$('#paymentPageStatus').className='status '+(b.payment==='PAID'?'success':b.payment==='REJECTED'?'danger':b.payment==='PROOF_SUBMITTED'?'info':'waiting');$('#paymentPageStatus').textContent=b.payment.replaceAll('_',' ');$('#verifyTitle').textContent=b.payment==='AWAITING_PAYMENT'?'Belum ada bukti':b.payment==='PROOF_SUBMITTED'?'Menunggu verifikasi admin':b.payment==='PAID'?'Pembayaran terverifikasi':'Bukti perlu diperbaiki';$('#paymentTimeline').innerHTML=timelineFor(b);const r=$('#screeningResult');if(!b.screening){r.className='screening-result neutral';r.innerHTML='<b>Belum dianalisis</b><p>Upload bukti transfer untuk menjalankan pre-screening.</p>'}else{const s=b.screening;const cls=s.duplicate||!s.amountMatch?'danger':s.score>=85?'good':'warn';r.className='screening-result '+cls;r.innerHTML=`<b>Pre-screening ${s.score}%</b><p>Nominal ${s.amountMatch?'cocok':'tidak cocok'} • Format ${s.fileOk?'valid':'bermasalah'} • Referensi ${s.reference?'ada':'kosong'} • Duplikat ${s.duplicate?'terdeteksi':'tidak terdeteksi'}. Tetap cek mutasi/rekening sebelum approve.</p>`}}
function renderUserBookings(){$('#userBookings').innerHTML=bookings.filter(b=>b.user.includes('Rayhandi')||b.id===state.invoiceId).map(b=>`<div class="booking-card"><div><span class="eyebrow dark">${b.id}</span><h3>${b.court}</h3><p>${b.date} • ${b.time}</p></div><div class="facts"><div><span>Payment</span>${statusChip(b.payment)}</div><div><span>Booking</span>${statusChip(b.booking)}</div><div><span>Total</span><b>${rupiah(b.total)}</b></div><div><span>Bukti</span><b>${b.proof?'Sudah diupload':'Belum ada'}</b></div></div><div><button class="btn light small" data-book-pay="${b.id}">Detail</button></div></div>`).join('');$$('[data-book-pay]').forEach(x=>x.onclick=()=>{state.invoiceId=x.dataset.bookPay;nav('payments')})}
function pending(){return bookings.filter(b=>b.payment==='PROOF_SUBMITTED')}
function renderQueue(){const list=pending();$('#verifyBadge').textContent=list.length;$('#notifCount').textContent=list.length;$('#mQueue').textContent=list.length;$('#adminQueueMetric').textContent=list.length;$('#adminQueueHome').innerHTML=list.length?list.slice(0,2).map(b=>`<div class="live-list"><div><i class="green"></i><div><b>${b.user} • ${rupiah(b.total)}</b><span>${b.id} • ${b.court}</span></div></div></div>`).join(''):'<p style="color:#7e8f86;font-size:9px">Tidak ada antrean pembayaran.</p>';$('#verificationQueue').innerHTML=list.length?list.map(b=>{const s=b.screening||{};return `<div class="verify-item"><div><span class="eyebrow dark">${b.id}</span><h3>${b.user} • ${b.court}</h3><p>${b.date} • ${b.time} • ${rupiah(b.total)}</p><div class="risk"><span class="${s.amountMatch?'ok':'warn'}">Nominal ${s.amountMatch?'cocok':'beda'}</span><span class="${s.duplicate?'warn':'ok'}">${s.duplicate?'Bukti duplikat':'Fingerprint unik'}</span><span>${s.score||0}% pre-screen</span></div></div><div><div class="summary-list"><div><span>Bank</span><b>${b.proof?.bank||'-'}</b></div><div><span>Referensi</span><b>${b.proof?.reference||'Tidak diisi'}</b></div></div></div><div class="verify-actions"><button class="btn light small" data-review="${b.id}">Review</button><button class="btn primary small" data-approve="${b.id}">Approve</button></div></div>`}).join(''):'<div class="card">Tidak ada pembayaran yang menunggu verifikasi.</div>';$$('[data-review]').forEach(x=>x.onclick=()=>openReview(x.dataset.review));$$('[data-approve]').forEach(x=>x.onclick=()=>openReview(x.dataset.approve))}
function openReview(id){const b=bookings.find(x=>x.id===id);if(!b)return;$('#reviewModal').classList.remove('hidden');$('#modalTitle').textContent=`${b.id} • ${b.user}`;const s=b.screening||{};$('#modalBody').innerHTML=`<div class="review-grid"><div class="proof-large"><div><b>${b.proof?.name||'Bukti tidak tersedia'}</b><p style="font-size:9px;color:#7e8f86">Preview gambar asli hanya tersedia pada sesi upload lokal prototype.</p></div></div><div><div class="review-facts"><div><span>Invoice</span><b>${rupiah(b.total)}</b></div><div><span>Nominal bukti</span><b>${rupiah(b.proof?.amount||0)}</b></div><div><span>Bank pengirim</span><b>${b.proof?.bank||'-'}</b></div><div><span>No. referensi</span><b>${b.proof?.reference||'-'}</b></div><div><span>Pre-screen</span><b>${s.score||0}%</b></div><div><span>Fingerprint duplikat</span><b>${s.duplicate?'TERDETEKSI':'Tidak'}</b></div></div><div class="decision-box"><b>Penting:</b> approve hanya setelah admin melihat mutasi/rekening dan memastikan dana benar-benar masuk.</div></div></div><div class="modal-actions"><button class="btn reject" data-reject-final="${id}">Tolak bukti</button><button class="btn primary" data-approve-final="${id}">Dana sudah masuk — Approve</button></div>`;$('#modalBody').querySelector('[data-approve-final]').onclick=()=>decide(id,true);$('#modalBody').querySelector('[data-reject-final]').onclick=()=>decide(id,false)}
function decide(id,approve){const b=bookings.find(x=>x.id===id);if(!b)return;b.payment=approve?'PAID':'REJECTED';b.booking=approve?'CONFIRMED':'PENDING';b.audit.push(`${approve?'Approved':'Rejected'} oleh Admin ${new Date().toLocaleString('id-ID')}`);save();$('#reviewModal').classList.add('hidden');renderAll();toast(approve?'Pembayaran dikonfirmasi. Booking menjadi CONFIRMED.':'Bukti ditolak. User perlu kirim ulang.')}
$('#closeModal').onclick=()=>$('#reviewModal').classList.add('hidden');
function renderAdminTables(){$('#adminBookingTable').innerHTML=bookings.map(b=>`<tr><td><b>${b.id}</b></td><td>${b.user}</td><td>${b.court}</td><td>${b.date}<br>${b.time}</td><td>${statusChip(b.payment)}</td><td>${statusChip(b.booking)}</td><td>${rupiah(b.total)}</td></tr>`).join('');$('#transactionTable').innerHTML=bookings.filter(b=>b.payment!=='AWAITING_PAYMENT').map((b,i)=>`<tr><td>TRX-${26091500+i+1}</td><td>${b.id}</td><td>${b.proof?'Transfer manual':'-'}</td><td>${rupiah(b.total)}</td><td>${statusChip(b.payment)}</td><td>${b.audit.at(-1)||'-'}</td></tr>`).join('')}
$('#penaltyToggle').onclick=e=>{state.penalty=!state.penalty;e.currentTarget.classList.toggle('on',state.penalty);e.currentTarget.textContent=state.penalty?'ON':'OFF';toast(`Denda ${state.penalty?'diaktifkan':'dinonaktifkan'}`)};
$$('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('Nomor rekening disalin.')}catch{toast('Salin manual: '+b.dataset.copy)}});
function renderAll(){renderCourts();renderWeek();renderSlots();renderEquipment();updateTotals();renderPayment();renderUserBookings();renderQueue();renderAdminTables()}
renderAll();